### ISSUE TITLE
Update aragonCLI documentation

### ISSUE THREAD

**Issue by 0xGabi** [aragon/hack#87]
Reasons discussed in https://github.com/aragon/aragon-cli/issues/364

### New Features:

- [x] `create-aragon-app` https://github.com/aragon/hack/issues/74

- [x] `dao act`

- [x] `dao token`

- [x] `apm grant`

- [x] `--environment` usage https://github.com/aragon/hack/issues/53

### Guides

- [x] Luke’s [guide](https://forum.aragon.org/t/guide-custom-aragon-organization-deployment-using-the-cli/507)

- [x] Publishing https://github.com/aragon/hack/issues/33

### FAQ

- [x] Initialization of global variables in apps https://github.com/aragon/hack/issues/76

- [x] Windows specific considerations https://github.com/aragon/hack/issues/77
Issue sending tx

- [x] Errors related to delete the ./ipfs directory

- [x] ipfs not running

- [x] How to verify contracts onchain

- [x] Explain when use the parameter wsRPC in arrap.json. Connect to custom endpoint

- [x] Set a private key to sign tx (https://aragon.chat/channel/dev-help?msg=KmDvP8YP27FjhfhWf)

- [x] Propagating content hash

- [x] ./aragon directory

### Update

- [x] Existing tutorial https://github.com/aragon/hack/issues/15

- [x] `init`

- [x] `run`

- [x] `devchain`

- [x] `dao new`

- [x] `dao upgrade`

- [x] `dao install`

- [x] `dao exec`

- [x] `apm publish`

- [x] Remove metamask https://github.com/aragon/hack/issues/70

Note: For a more in depth review [check this file](https://docs.google.com/document/d/1TA3C1IMyll6rxF7gZBASGNKo8lkucW0PmHXhd3lzUOE/edit#)

**Comment by 0xGabi** [comment]
Close with #99
